const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        title: 'Pashupati Jewellers APIs',
        description: 'API documentation for the inventory',
        version: '1.0.0',
    },
    host: 'localhost:3000',
    schemes: ['http'],
    definitions: {
        Category: {
            type: "object",
            properties: {
                id: {
                    type: "string",
                    description: "Unique identifier for the category, generated by MongoDB",
                    example: "614c2f15f2d2b1944a5bb4b5"
                },
                name: {
                    type: "string",
                    description: "Name of the category",
                    example: "Rings"
                }
            },
            required: ["name"]
        },
        Product: {
            type: "object",
            properties: {
                id: {
                    type: "string",
                    description: "Unique identifier for the product, generated by MongoDB",
                    example: "64d8f9349c4f99e3db7b0a25"
                },
                title: {
                    type: "string",
                    description: "Name of the product",
                    example: "Gold Ring"
                },
                imageNames: {
                    type: "array",
                    items: {
                        type: "string",
                    },
                    description: "List of image file names",
                    example: ["image1.jpg", "image2.jpg"]
                },
                description: {
                    type: "string",
                    description: "Detailed description of the product",
                    example: "A beautiful gold ring."
                },
                amount: {
                    type: "number",
                    description: "Amount or stock quantity of the product",
                    example: 10
                },
                category: {
                    type: "string",
                    description: "ID of the product's category",
                    example: "614c2f15f2d2b1944a5bb4b5"
                },
                gender: {
                    type: "string",
                    enum: ["male", "female", "unisex"],
                    description: "Gender specification of the product",
                    example: "unisex"
                },
                metalType: {
                    type: "string",
                    enum: ["gold", "silver", "platinum", "other"],
                    description: "Metal type of the product",
                    example: "gold"
                }
            },
            required: ["title", "imageNames", "description", "category", "gender", "metalType"]
        }
    }
};

const outputFile = './swagger-output.json'; // Path to generated swagger file
const endpointsFiles = ['./src/routes/**/*.js', './src/index.js', './src/controllers/*.js', './src/repository/*.js']; // Path to your main route file

swaggerAutogen(outputFile, endpointsFiles, doc);
